version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8800:80"
  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8801:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
volumes:
  dbdata:
